config/routes.rb
SatEngine::Engine.routes.draw do

  resources :sat_questions, only: [:questions_for_granule] do
    member do
      get :preview
      get :show_image
    end
    collection do 
      get :questions_for_granule
    end
  end

  resources :sat_uploads do
    member do
      get :load_sat_questions
    end
  end
  
  resources :sat_papers do
    collection do
      get :curriculum_navigation
      get :year_navigation
      get :level_navigation
    end
  end

  get '/terms_and_conditions' => 'dashboard#terms_and_conditions', :as => :terms_and_conditions
  get '/privacy_policy' => 'dashboard#privacy_policy', :as => :privacy_policy

  root :to => 'dashboard#index'
end

app/models/sat_engine/granule_sat_question_alternative.rb
module SatEngine
  class GranuleSatQuestionAlternative < ActiveRecord::Base
    attr_accessible :granule_position, :sat_question_id, :deleted, :deleted_at

    belongs_to :alternative_sat_questions, class_name: SatEngine::SatQuestion.to_s, foreign_key: :sat_question_id
    belongs_to :granule, foreign_key: :granule_position, primary_key: :position

    scope :available, -> { where(:deleted => false) }

    def self.mark_as_destroyed_all!
      GranuleSatQuestionAlternative.update_all(deleted: true, deleted_at: Time.zone.now)
    end

    def mark_as_destroyed!
      update_attribute(:deleted, true)
      update_attribute(:deleted_at, Time.zone.now)
    end

  end
end

app/models/sat_engine/selected_question.rb
module SatEngine
  class SelectedQuestion < ActiveRecord::Base
    # title - each question contains unique title according to navigation. 
    # For example, Centimetres( it means it was accessed throw the curriculum navigation )
    # sat_question_id - foreign key for SatQuestion
    # position - the position in which we will be putting questions to pdf
    attr_accessible :title, :sat_question_id, :position
    belongs_to :sat_paper
    belongs_to :sat_question
  end
end

app/controllers/sat_engine/application_controller.rb
module SatEngine
  class ApplicationController < ActionController::Base
    layout 'layouts/application' 

    def authenticate_tutor_or_tutor_admin_or_admin_or_academic_councillor!
      redirect_to main_app.home_path unless current_user.academic_councillor? or current_user.tutor_admin? or current_user.admin? or current_user.tutor?
    end

    def authenticate_admin!
      redirect_to main_app.home_path unless current_user.admin?
    end

  end
end

app/controllers/sat_engine/sat_papers_controller.rb
module SatEngine
  class SatPapersController < SatEngine::ApplicationController
    before_filter :authenticate_user!
    before_filter :authenticate_tutor_or_tutor_admin_or_admin_or_academic_councillor!
    
    def new
      @sat_paper = SatPaper.new
    end

    def create
      @sat_paper = SatPaper.new
      unless params[:sat_questions].present?
        flash[:error] = I18n.t('sat_papers.error.no_selection')
        return respond_to do |format|
          format.html { redirect_to new_sat_paper_path }
        end
      end
      
      selected_questions = find_sat_paper_questions(@sat_paper, params[:sat_questions])
      if @sat_paper.save
        flash[:success] = I18n.t('sat_papers.success')

        respond_to do |format|          
          format.html do 
            redirect_to sat_paper_path(@sat_paper) 
          end

          format.pdf {
            pdf = paper_to_pdf
            render :text => pdf
          }
        end
      else
        flash[:error] = I18n.t('sat_papers.error.default')
        render :new
      end
    end

    def show
      @sat_paper = SatPaper.find(params[:id])
      
      # request pdf url from API
      response = @sat_paper.request_pdf
      @sat_paper_url = response['url']

      if @sat_paper_url.blank?
        flash[:error] = I18n.t('sat_papers.error.not_available')
        redirect_to main_app.home_path
      end
    end
    
    def curriculum_navigation
      if params[:filter]
        @granules = Granule.all_active_granules.filter(params[:filter], params[:value]).page(params[:page]).per(20)
        return render :json => {:content => render_to_string(:action => :curriculum_navigation_table)}
      end
      if params[:search]
        @term = params[:search]
        @granules = Granule.all_active_granules.search(params[:search]).page(params[:page]).per(20)
        return render :json => {:content => render_to_string(:action => :curriculum_navigation_table)}
      end
      @granules = Granule.all_active_granules.page(params[:page]).per(20)
      return respond_to do |format|
        format.html { render :layout => false }
        format.json { render :json => {:content => render_to_string(:action => :curriculum_navigation)} }
      end
    end
    
    def year_navigation
      render :layout => false
    end
    
    def level_navigation
      render :layout => false
    end

    private
    def find_sat_paper_questions sat_paper, sat_questions_params
      sat_questions = SatQuestion.where(id: sat_questions_params[:id]).order("field(id, #{sat_questions_params[:id].join(',')})")

      sat_questions.each_with_index do |sat_question, index|
        sat_paper.selected_questions.build(sat_question_id: sat_question.id, title: sat_questions_params[:granule_name][index])
      end
    end

    def upload_paper
      
    end

    # @deprecated [Supply link only by @sat_paper.request_pdf]
    def paper_to_pdf
      if Settings.generate_sat_paper_on_api
        response = @sat_paper.request_pdf
        pdf = response['success'] ? @sat_paper.remote_pdf_file(response['url']) : nil
      else
        html = render_to_string(:action => :show, :formats => [:pdf])
        pdf = @sat_paper.to_pdf(html)
      end
    end

  end
end

app/controllers/sat_engine/sat_questions_controller.rb
  module SatEngine
    class SatQuestionsController < ApplicationController
    before_filter :authenticate_user!
    before_filter :authenticate_tutor_or_tutor_admin_or_admin_or_academic_councillor!

    def preview
      @granule_name = params[:granule_name]
      @sat_question = SatQuestion.find(params[:id])
      respond_to do |format|
        format.json { render :json => {:success => true, :content => render_to_string(:action => :preview) } }
      end
    end

    def questions_for_granule
      all_granule_sat_questions_hash = SatQuestion.all_questions_for_granule_hash(params[:granule_position])

      respond_to do |format|
        format.html { flash[:error] = "Invalid request"; redirect_to home_path }
        format.json { render :json => {:success => true, :content => render_to_string(partial: 'questions_for_granule', locals: { sat_questions: all_granule_sat_questions_hash })} }
      end
    end

    def show_image
      @sat_question = SatQuestion.find(params[:id])
      @image = question_file_from_type(@sat_question, params[:type])

      send_data @image, :type => 'image/png', :disposition => 'inline'
    end

    private
    def question_file_from_type sat_question, type
      case type.to_s
      when 'question' then return @sat_question.question_file
      when 'mark_scheme' then return @sat_question.mark_scheme_file
      end
    end

  end
end

app/controllers/sat_engine/sat_uploads_controller.rb
module SatEngine
  class SatUploadsController < SatEngine::ApplicationController
    before_filter :authenticate_user!
    before_filter :authenticate_admin!
    before_filter :validate_sat_questions_csv!, :only => [:load_sat_questions]

    def new
      @sat_upload = SatUpload.new
    end
    
    def create
      @sat_upload = SatUpload.new(params[:sat_upload])
      if @sat_upload.save
        @sat_upload.update_attribute(:finished, true)
        flash[:success] = I18n.t('sat_uploads.success')
        redirect_to sat_upload_path(@sat_upload)
      else
        flash[:error] = I18n.t('sat_uploads.error')
        render :action => :new
      end
    end
    
    def show
      @sat_upload = SatUpload.find(params[:id])
    end

    # TODO: Move flash to EN file
    def load_sat_questions
      @sat_upload = SatUpload.find(params[:id])
      @sat_upload.load_sat_questions
      flash[:success] = I18n.t('sat_uploads.load_sat_questions.success')
      redirect_to new_sat_paper_url
    end

    protected
    def validate_sat_questions_csv!
      sat_upload = SatUpload.find(params[:id])
      if sat_upload.valid_csv_file
        headers_validation_result = sat_upload.validate_sat_question_headers
        if (headers_validation_result[:success])
          return true
        else
          flash[:error] = I18n.t('sat_uploads.load_sat_questions.error.list_errors', errors: headers_validation_result[:errors].join('; '))
          redirect_to action: :show
        end
      else
        flash[:error] =  I18n.t('sat_uploads.load_sat_questions.error.validation_error')
        redirect_to action: :show
      end
    end

  end
end

app/helpers/sat_engine/application_helper.rb
module SatEngine
  module ApplicationHelper

  	def pluralize count, noun
  		if count != 0
		    count == 1 ? "#{count} #{noun}" : "#{count} #{noun.pluralize}"
		  end
  	end

  	def shortened_granule_name name
			return if name.nil?
			if name.length > 24
				return name[0..24] + '...'
			else
				return name
			end
		end

    # TODO Extract to separate class
		def rescale_sat_question_image image_size
      # max sizes are defined according to
      # pdf landscape and positioning elements on it
      max_paper_height = 550
      max_paper_width = 600

      tall_img_max_width = 625
      short_img_constrain = 390
      ################################################

      width = image_size[0]
      height = image_size[1]
      landscape_image = landscape_image?(width, height)

      ratio = image_ratio(width, height, landscape_image)
      scaled_height = rescale_height(max_paper_width, ratio, landscape_image)

      # image is short - use whole page width
      if scaled_height < short_img_constrain
        new_height = max_paper_height
        new_width = rescale_width(max_paper_height, ratio, landscape_image)

        # height is fine - but width doesn't fit
        if new_width > max_paper_width
          new_width = max_paper_width
          new_height = rescale_height(new_width, ratio, landscape_image)
        end
      else # image is tall - make space for marks
        new_width = tall_img_max_width
        new_height = rescale_height(new_width, ratio, landscape_image)

        if new_height > max_paper_height
          new_height = max_paper_height
          new_width = rescale_width(new_height, ratio, landscape_image)
        end
      end

      { width: new_width, height: new_height }
    end

   def rescale_mark_scheme_image image_size
      # max sizes are defined according to
      # pdf landscape and positioning elements on it
      max_mark_scheme_height = 445
      max_mark_scheme_width = 855

      width = image_size[0]
      height = image_size[1]
      ###############################################

      landscape_image = landscape_image?(width, height)
      ratio = image_ratio(width, height, landscape_image)
      scaled_height = rescale_height(max_mark_scheme_height, ratio, landscape_image)
      scaled_width = rescale_width(scaled_height, ratio, landscape_image)

      if height > scaled_height
        new_height = max_mark_scheme_height
        new_width = rescale_width(new_height, ratio, landscape_image)

        if new_width > max_mark_scheme_width
          new_width = max_mark_scheme_width
          new_height = rescale_height(new_width, ratio, landscape_image)
        end
      else
        new_width = scaled_height
        new_height = scaled_width
      end

      { width: new_width, height: new_height }
    end

    def image_ratio width, height, landscape_orientation
      if landscape_orientation
        (width.to_f / height.to_f)
      else
        (height.to_f / width.to_f)
      end
    end

    def rescale_width height, ratio, landscape_orientation
      if landscape_orientation
        width = height * ratio
      else
        width = height / ratio
      end
      width
    end

    def rescale_height width, ratio, landscape_orientation
      if landscape_orientation
        height = width / ratio
      else
        height = width * ratio
      end
      height
    end

    def landscape_image? width, height
      width > height
    end

    def sat_question_page_index index
      return 1 if index == 0
      (index * 2 + 1)
    end

    def paper_pdf_link url
      url.present? ? url : '#'
    end

    def disabled_pdf_link? url
       url.nil? ? 'disabled' : nil
    end

    def local_request?
      Rails.env.development? or request.remote_ip =~ /(::1)|(127.0.0.1)|((192.168).*)/
    end

    def set_body_class
      params[:controller].to_s+'-'+params[:action].to_s
    end

    def logo_url
      return main_app.calendar_path if current_user.present? and current_user.tutor?
      main_app.home_path
    end

    def set_nav_current_item when_selected_array
      return 'current-item' if when_selected_array.include?(params[:controller])
      ''
    end

    def set_current_item_by_action when_selected_array
      return 'current-item' if when_selected_array.include?(params[:action])
      ''
    end

    def set_current_item_by_controller_and_action when_selected_hash
      if when_selected_hash[:controller] == params[:controller] and when_selected_hash[:action] == params[:action]
        return 'current-item'
      end
      ''
    end

    def set_current_item_by_controller_and_action_by_array when_selected_hash_array
      when_selected_hash_array.each do |when_selected_hash|
        if when_selected_hash[:controller] == params[:controller] and when_selected_hash[:action] == params[:action]
          return 'current-item'
        end
      end
      ''
    end

    def reports_dropdown_hash_array
      [
        {controller: "reports", action: 'learning_objective'},
        {controller: "reports", action: 'student_performance'},
        {controller: "reports", action: 'student_details'},
        {controller: "reports", action: 'weekly_tutor'},
        {controller: "reports", action: 'weekly_school'},
        {controller: "reports", action: 'sittings'},
        {controller: "reports", action: 'authorities_schools'},
        {controller: "reports", action: 'school_map'},
        {controller: "reports", action: 'school_setup_progress'},
        {controller: "learning_session_reassignments", action: 'index'},
        {controller: "delayed_exports", action: 'index'}
      ]
    end

    def accounts_dropdown_hash_array
      [
        {controller: "accounts", action: 'review'},
        {controller: "teachers", action: 'index'},
        {controller: "learning_groups", action: 'index'},
        {controller: "tutors", action: 'index'},
        {controller: "tutor_admins", action: 'index'},
        {controller: "supply_tutors", action: 'index'}
      ]
    end

    def curriculum_dropdown_hash_array
      [
        {controller: "curriculum", action: 'index'},
        {controller: "granules", action: 'index'},
        {controller: "reports", action: 'granule_history'},
        {controller: "granules", action: 'new'}
      ]
    end

    def sessions_dropdown_hash_array
      [
        {controller: "learning_sessions", action: 'completed'},
        {controller: "learning_sessions", action: 'sessions_tracker'},
        {controller: "learning_sessions", action: 'upcoming'}
      ]
    end

    def contracts_dropdown_hash_array
      [
        {controller: "contracts", action: 'add'},
        {controller: "contracts", action: 'index'}
      ]
    end

    def tutor_sessions_dropdown_hash_array
      [
        {controller: "learning_sessions", action: 'completed'},
        {controller: "calendar", action: 'index'},
        {controller: "devise_controllers/users", action: 'individual_kosmos_sessions'}
      ]
    end

    def error_message_builder object
      content_tag :div, :id => 'errorExplanation' do
        content_tag :ul do
          content = ''
          object.errors.full_messages.each do |msg|
            content += content_tag :li, msg, :class => 'error'
          end
          raw content
        end
      end
    end

    def date_format time, format = :long
    case format
    when :full then time.strftime('%d-%m-%Y %I:%M%p')
    end
  end

  end
end

app/helpers/sat_engine/granule_helper.rb
module SatEngine
  module GranuleHelper
    def display_topic_name granule
      if granule.nil?
        "-"
      else
        granule.full_name
      end
    end
    
    def granule_year_select
      a = CurriculumLevel.
        available.
        select("curriculum_levels.name").
        uniq("curriculum_levels.name").
        order("curriculum_levels.name").map do |level|
          [level.name[4..-1], level.name]
      end
      a.unshift("-")
      return a
    end
    
    def granule_category_select
      a = CurriculumCategory.
        available.
        select("curriculum_categories.name").
        uniq("curriculum_categories.name").
        order("curriculum_categories.name").map do |category|
          [category.name, category.name]
      end
      a.unshift("-")
      return a
    end
    
    def granule_topic_select
      a = CurriculumTopic.
        available.
        select("curriculum_topics.name").
        uniq("curriculum_topics.name").
        order("curriculum_topics.name").map do |topic|
          [topic.name, topic.name]
      end
      a.unshift("-")
      return a
    end
    
    def granule_level_select
      a = Granule.available.select("DISTINCT level").order(:level).map do |granule|
        [granule.level, granule.level]
      end
      a.unshift("-")
      return a
    end
    
    def highlight_granule_search_term text, term
      if term.nil?
        text
      else
        text.gsub(/(#{term})/i) { |t| "<b class='red-link'>#{t}</b>" }.html_safe
      end
    end
  end
end

app/views/sat_engine/sat_papers/_pdf_footer.pdf.erb
<%# TODO: DELETE if not used %>

<style type="text/css">
	.sat-pdf-footer{
		margin-bottom: -10px;
		background-color: #2583F1;
		height: 20px;
		padding: 10px;


	  height: 277mm;
	  overflow: hidden;
	}
</style>

<div class="sat-pdf-footer">Footer</div>

app/views/sat_engine/sat_papers/curriculum_navigation.html.erb
<div class="sat_curriculum_navigation">
  <div class="entry-content">
    <%= link_to "Show All", curriculum_navigation_sat_papers_path, :id => "sat_curriculum_navigation_link", :class => "btn btn-medium" %>
    <div class="ui-helper-clearfix"></div>
    <br>
    <div class="label-input">
      <label>Search</label>
      <%= text_field_tag :sat_search_granule_text, "", :placeholder => "Search for LO, topic" %>
      <%= link_to "Search", curriculum_navigation_sat_papers_path, :id => "sat_curriculum_navigation_search_button", :class => "btn btn-medium b-right" %>
    </div>
    <hr>
    <br>
    <div class="col2">
      <div class="label-input">
        <label>Category</label>
        <%= select_tag :category, options_for_select(granule_category_select), :class => "sat-filter-granule", :"data-href" => curriculum_navigation_sat_papers_path %>
      </div>
      <div class="label-input">
        <label>Topic</label>
        <%= select_tag :topic, options_for_select(granule_topic_select), :class => "sat-filter-granule", :"data-href" => curriculum_navigation_sat_papers_path %>
      </div>
    </div>
    <div class="col2">
      <div class="label-input">
        <label>Year</label>
        <%= select_tag :year, options_for_select(granule_year_select), :class => "sat-filter-granule", :"data-href" => curriculum_navigation_sat_papers_path %>
      </div>
      <div class="label-input">
        <label class="curriculum-level-label">Curriculum Level</label>
        <%= select_tag :level, options_for_select(granule_level_select), :class => "sat-filter-granule", :"data-href" => curriculum_navigation_sat_papers_path %>
      </div>
    </div>
  </div>
  <hr>
  <br>
  <div id="sat-granule-table">
    <div class="sat-main-granule-pagination" data-href="<%= curriculum_navigation_sat_papers_path %>">
      <%= paginate @granules -%>
    </div>
    <table class="tsl-table">
      <thead class="tsl-table__thead">
        <tr class="tsl-table__tr">
          <th class="tsl-table__th">Year</a></th>
          <th class="tsl-table__th">Category</a></th>
          <th class="tsl-table__th">Topic</th>
          <th class="tsl-table__th">Lesson title</th>
          <th class="tsl-table__th">Level</th>
        </tr>
      </thead>
      <tbody>
        <% @granules.each do |granule| -%>
          <tr class='<%= cycle('tsl-table__tr--gray', 'tsl-table__tr--white') %> sat-curriculum-granule' data-granule-position='<%=granule.position %>'>
            <td class="tsl-table__td"><%= granule.curriculum_level_name[4..-1] %></td>
            <td class="tsl-table__td"><%= highlight_granule_search_term(granule.curriculum_category_name, @term) %></td>
            <td class="tsl-table__td"><%= highlight_granule_search_term(granule.curriculum_topic_name, @term) %></td>
            <td class="tsl-table__td"><%= highlight_granule_search_term(granule.granule_name, @term) %></td>
            <td class="tsl-table__td"><%= highlight_granule_search_term(granule.level, @term) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/sat_engine/sat_papers/curriculum_navigation.json.erb
<div class="entry-content">
  <%= link_to "Show All", curriculum_navigation_sat_papers_path, :id => "sat_curriculum_navigation_link", :class => "btn btn-medium" %>
  <div class="ui-helper-clearfix"></div>
  <br>
  <div class="label-input">
    <label>Search</label>
    <%= text_field_tag :sat_search_granule_text, "", :placeholder => "Search for LO, topic" %>
    <%= link_to "Search", curriculum_navigation_sat_papers_path, :id => "sat_curriculum_navigation_search_button", :class => "btn btn-medium b-right" %>
  </div>
  <hr>
  <br>
  <div class="col2">
    <div class="label-input">
      <label>Category</label>
      <%= select_tag :category, options_for_select(granule_category_select), :class => "sat-filter-granule", :"data-href" => curriculum_navigation_sat_papers_path %>
    </div>
    <div class="label-input">
      <label>Topic</label>
      <%= select_tag :topic, options_for_select(granule_topic_select), :class => "sat-filter-granule", :"data-href" => curriculum_navigation_sat_papers_path %>
    </div>
  </div>
  <div class="col2">
    <div class="label-input">
      <label>Year</label>
      <%= select_tag :year, options_for_select(granule_year_select), :class => "sat-filter-granule", :"data-href" => curriculum_navigation_sat_papers_path %>
    </div>
    <div class="label-input">
        <label class="curriculum-level-label">Curriculum Level</label>
      <%= select_tag :level, options_for_select(granule_level_select), :class => "sat-filter-granule", :"data-href" => curriculum_navigation_sat_papers_path %>
    </div>
  </div>
</div>
<hr>
<br>
<div id="sat-granule-table">
  <div class="sat-main-granule-pagination" data-href="<%= curriculum_navigation_sat_papers_path %>">
    <%= paginate @granules -%>
  </div>
  <table class="tab-blue ta">
    <thead>
    <tr>
      <th><a href="#">Year</a></th>
      <th><a href="#">Category</a></th>
      <th><a href="#">Topic</a></th>
      <th><a href="#">Lesson title</a></th>
      <th><a href="#">Level</a></th>
    </tr>
    </thead>
    <tbody>
    <% @granules.each do |granule| -%>
      <tr class='sat-curriculum-granule' data-granule-position='<%=granule.position %>'>
        <td><%= granule.curriculum_level_name[4..-1] %></td>
        <td><%= highlight_granule_search_term(granule.curriculum_category_name, @term) %></td>
        <td><%= highlight_granule_search_term(granule.curriculum_topic_name, @term) %></td>
        <td><%= highlight_granule_search_term(granule.granule_name, @term) %></td>
        <td><%= highlight_granule_search_term(granule.level, @term) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/sat_engine/sat_papers/curriculum_navigation_table.json.erb
<% if @granules.empty? %>
  <h1 class="center-text">Couldn't find any learning objectives</h1>
<% else %>
  <div class="sat-granule-pagination">
    <%= paginate @granules -%>
  </div>
  <table class="tsl-table">
    <thead class="tsl-table__thead">
      <tr class="tsl-table__tr">
        <th class="tsl-table__th">Year</th>
        <th class="tsl-table__th">Category</th>
        <th class="tsl-table__th">Topic</th>
        <th class="tsl-table__th">Lesson title</th>
        <th class="tsl-table__th">Level</th>
      </tr>
    </thead>
    <tbody>
      <% @granules.each do |granule| -%>
        <tr class='<%= cycle('tsl-table__tr--gray', 'tsl-table__tr--white') %> sat-curriculum-granule' data-granule-position='<%=granule.position %>'>
          <td class="tsl-table__td"><%= granule.curriculum_level_name[4..-1] %></td>
          <td class="tsl-table__td"><%= highlight_granule_search_term(granule.curriculum_category_name, @term) %></td>
          <td class="tsl-table__td"><%= highlight_granule_search_term(granule.curriculum_topic_name, @term) %></td>
          <td class="tsl-table__td">
          <% if @learning_session %>
            <label title="<%= granule.description %>"><%= highlight_granule_search_term(granule.granule_name, @term) %></label>
          <% else %>
            <%= highlight_granule_search_term(granule.granule_name, @term) %>
          <% end %>
         </td>
          <td><%= highlight_granule_search_term(granule.level, @term) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/sat_engine/sat_papers/level_navigation.html.erb
<div class="message">
  Not implemented
</div>

app/views/sat_engine/sat_papers/new.html.erb
<div id="content">
    <div class="sat_navigation sat_navigation_block">
      <div class="tsl-tabs">
        <ul>
          <li class="tsl-tabs__tab-item">
            <%= link_to 'Curriculum Navigation', curriculum_navigation_sat_papers_path, class: "tsl-tabs__tab-link", id: "curriculum-navigation-tab" %>
          </li>
          <li class="tsl-tabs__tab-item">
            <%= link_to 'Year', year_navigation_sat_papers_path, class: "tsl-tabs__tab-link", id: "year-navigation-tab" %>
          </li>
          <li class="tsl-tabs__tab-item">
            <%= link_to 'Level', level_navigation_sat_papers_path, class: "tsl-tabs__tab-link", id: "level-navigation-tab" %>
          </li>
        </ul>
      </div>
      <br>
      <%= link_to 'Replace Sat Questions', new_sat_upload_path, :class => 'btn btn-auto btn-medium b-right' %>
    </div>

    <div class="sat_sidebar sat_sidebar_block">
      <table class="tab-blue ta tab-matched-questions droptrue" id='table-draggable1' style="margin-bottom:15px;">
        <thead>
          <tr class="question-block-header">

            <th>Matched questions</th>

          </tr>
        </thead>
        <tbody class='sat-matched-questions connectedSortable'>
        </tbody>
      </table>
      <%= form_for(@sat_paper, format: [:html],  :html => { :target => '_blank' }) do |f| %>
        <table id='table-draggable2' class="tab-blue ta ta-dragable" class="droptrue">
          <thead>
            <tr class="question-block-header">

              <th>Selected questions</th>

            </tr>
          </thead>
          <tbody class="connectedSortable sat-selected-questions">
          </tbody>
        </table>
        <%= f.submit 'Generate Pdf', class: "btn btn-auto btn-medium  b-right" %>
      <% end %>
    </div>
    <div class="ui-helper-clearfix"></div>
</div>

app/views/sat_engine/sat_papers/show.html.erb
<div id="content">
  <div class="section-border">
    <h2>Sat Question Paper</h2>
  	<%= link_to 'Download Pdf', paper_pdf_link(@sat_paper_url), target: 'blank', class: "btn btn-medium btn-auto #{disabled_pdf_link?(@sat_paper_url)}" %>
  </div>
</div>

app/views/sat_engine/sat_papers/year_navigation.html.erb
<div class="message">
  Not implemented
</div>